// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCCsgA4RKut5vAFTli9vx56HYv_wJiJQ',
    appId: '1:274986368110:web:c0f4780c56e7226d63ba7f',
    messagingSenderId: '274986368110',
    projectId: 'debongo-app-7999',
    authDomain: 'debongo-app-7999.firebaseapp.com',
    storageBucket: 'debongo-app-7999.appspot.com',
    measurementId: 'G-XPX9T964ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKB-Q2tr0n3TfnTcKd1bcJSle89EUWWB0',
    appId: '1:274986368110:android:17cf412c268cdf0163ba7f',
    messagingSenderId: '274986368110',
    projectId: 'debongo-app-7999',
    storageBucket: 'debongo-app-7999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSzVq368Zhd7aibTTTcgMiywIRhQVevk',
    appId: '1:274986368110:ios:7c3e0ee6576899d463ba7f',
    messagingSenderId: '274986368110',
    projectId: 'debongo-app-7999',
    storageBucket: 'debongo-app-7999.appspot.com',
    androidClientId: '274986368110-qaqfs6d4jjp5gl21eg6ssokainls50c9.apps.googleusercontent.com',
    iosClientId: '274986368110-qe11pped2vruivnojiegs9ej3dgfid01.apps.googleusercontent.com',
    iosBundleId: 'com.example.debongoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSzVq368Zhd7aibTTTcgMiywIRhQVevk',
    appId: '1:274986368110:ios:9c010263380ef27a63ba7f',
    messagingSenderId: '274986368110',
    projectId: 'debongo-app-7999',
    storageBucket: 'debongo-app-7999.appspot.com',
    androidClientId: '274986368110-qaqfs6d4jjp5gl21eg6ssokainls50c9.apps.googleusercontent.com',
    iosClientId: '274986368110-5ubhq7dc6vqkn9dsckpa3aog95sjpgcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.debongoApp.RunnerTests',
  );
}
